name: Build Plugins

on:
  workflow_dispatch:   # run only when manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'Artemis-RGB/Artemis.PluginTemplate' && '[ -f .template ]' }}

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src/Artemis.Plugins.SerialInput/Artemis.Plugins.SerialInput.csproj

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Artemis.Plugins.SerialInput-build
          path: src/Artemis.Plugins.SerialInput/bin/x64/Release/net7.0/publish
